//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutTracker.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class workout_collection
    {
        public workout_collection()
        {
            this.workout_active = new HashSet<workout_active>();
        }
    
        public int workout_id { get; set; }
        public int category_id { get; set; }
        public string workout_title { get; set; }
        public string workout_note { get; set; }
        public double calories_burn_per_min { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<workout_active> workout_active { get; set; }
        public virtual workout_category workout_category { get; set; }
    }
}
